services:
  server:
    image: 503561432877.dkr.ecr.us-east-2.amazonaws.com/holisticherbhealth/nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    env_file:
      - ./env/nginx.env
    depends_on:
      - php
      - mysql
  php:
    image: 503561432877.dkr.ecr.us-east-2.amazonaws.com/holisticherbhealth/php:latest
    env_file:
      - ./src/.env.local
    depends_on:
      - mysql
  composer:
    image: chidodesigns/holisticherbhealth-composer
  artisan:
    image: 503561432877.dkr.ecr.us-east-2.amazonaws.com/holisticherbhealth/php:latest
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:22-alpine
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
  mysql_test:
    image: mysql:8.0
    volumes:
      - mysqltestdata:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    env_file:
      - ./env/mysql-test.env
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   restart: unless-stopped
volumes:
  mysqldata:
  mysqltestdata:
