name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-2
  ECR_NGINX_REPOSITORY: holisticherbhealth/nginx
  ECR_PHP_REPOSITORY: holisticherbhealth/php
  ECS_SERVICE: holisticherbhealth-service-v1
  ECS_CLUSTER: holisticherbhealthcluster
  ECS_TASK_DEFINITION: ./aws/dev-task-definition.json
  CONTAINER_NAME_NGINX: holisticherbhealth-server
  CONTAINER_NAME_PHP: holisticherbhealth-api

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Specify your PHP version
          coverage: none
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: deps-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            deps-composer-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --no-progress --ignore-platform-reqs
      - name: Run PHP CodeSniffer
        working-directory: ./src
        run: composer codesniff
      - name: Run PHP Code Beautify
        working-directory: ./src
        run: composer codebeautify

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Specify your PHP version
          coverage: none
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: deps-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            deps-composer-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --no-progress --ignore-platform-reqs
      - name: Run tests
        id: run-tests
        working-directory: ./src
        run: composer run-tests

  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push NGINX Image to Amazon ECR
        id: build-nginx-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_NGINX_REPOSITORY:$IMAGE_TAG -f ./dockerfiles/nginx.dockerfile .
          docker push $ECR_REGISTRY/$ECR_NGINX_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_NGINX_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build, tag, and push PHP Image to Amazon ECR
        id: build-php-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_PHP_REPOSITORY:$IMAGE_TAG -f ./dockerfiles/php.dockerfile .
          docker push $ECR_REGISTRY/$ECR_PHP_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_PHP_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME_NGINX }}
          image: ${{ steps.build-nginx-image.outputs.image }}
          container-name-2: ${{ env.CONTAINER_NAME_PHP }}
          image-2: ${{ steps.build-php-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true