name: 
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Install Composer Dependencies
          uses: actions/checkout@v3
          working-directory: ./src
          run: composer install --prefer-dist
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Suite
        uses: actions/checkout@v3
        working-directory: ./src
        run: composer run-tests